jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh-keyscan -H <YOUR_EC2_PUBLIC_IP> >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i private_key.pem ec2-user@<YOUR_EC2_PUBLIC_IP> << 'EOF'
          cd /home/ec2-user/apna_collage
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        EOF
